# Generated by Django 3.2.5 on 2021-09-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_id', models.CharField(db_column='log_id', max_length=20)),
                ('login_passwd', models.CharField(db_column='passwd', max_length=120)),
            ],
            options={
                'db_table': 'tb_super',
            },
        ),
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('c_id', models.AutoField(db_column='c_id', primary_key=True, serialize=False)),
                ('c_name', models.CharField(db_column='c_name', max_length=30)),
                ('c_desc', models.CharField(db_column='c_desc', max_length=200)),
                ('c_img', models.ImageField(db_column='c_img', upload_to='Category/')),
            ],
            options={
                'db_table': 'tb_category',
            },
        ),
        migrations.CreateModel(
            name='CraftDetails',
            fields=[
                ('cr_id', models.AutoField(db_column='cr_id', primary_key=True, serialize=False)),
                ('cr_name', models.CharField(db_column='cr_name', max_length=30)),
                ('cr_type', models.CharField(db_column='c_type', max_length=20)),
                ('prod_no', models.CharField(db_column='p_no', max_length=20)),
                ('cr_color', models.CharField(db_column='cr_clr', max_length=10)),
                ('cr_material', models.CharField(db_column='cr_material', max_length=20)),
                ('cr_desc', models.CharField(db_column='cr_desc', max_length=200)),
                ('cr_exp_days', models.IntegerField(db_column='p_exp')),
                ('cr_rating', models.FloatField(db_column='cr_rating', default=3.72)),
                ('cr_price', models.FloatField(db_column='price', default=0.0)),
                ('cr_sales_pack', models.CharField(db_column='package', max_length=30)),
                ('cr_img', models.ImageField(db_column='cr_img', upload_to='Seller/Products')),
                ('cr_stock', models.IntegerField(db_column='p_stock', default=0)),
                ('cr_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tb_craft',
            },
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(db_column='c_name', max_length=30)),
                ('cust_address', models.CharField(db_column='c_address', max_length=255)),
                ('cust_phno', models.CharField(db_column='c_phno', max_length=10)),
                ('cust_email', models.CharField(db_column='c_email', max_length=40)),
                ('cust_passwd', models.CharField(db_column='c_passwd', max_length=40)),
                ('cust_img', models.ImageField(db_column='c_img', upload_to='Customer/')),
            ],
            options={
                'db_table': 'tb_customer',
            },
        ),
        migrations.CreateModel(
            name='GardenIdeas',
            fields=[
                ('req_id', models.AutoField(db_column='req_id', primary_key=True, serialize=False)),
                ('plot_pic', models.ImageField(db_column='plot_pic', upload_to='Ideas/Garden')),
                ('requirements', models.CharField(db_column='req', max_length=255)),
                ('exp_date', models.CharField(db_column='exp_date', max_length=10)),
                ('budget', models.FloatField(db_column='budget')),
                ('date_posted', models.CharField(db_column='date_posted', max_length=10)),
                ('est_date', models.CharField(db_column='est_date', max_length=10)),
                ('status', models.CharField(db_column='status', max_length=20)),
                ('reject_reason', models.CharField(db_column='r_reason', max_length=100)),
                ('plot_design', models.ImageField(upload_to='Ideas/Garden/Design')),
                ('cust_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.customerdetails')),
            ],
            options={
                'db_table': 'tb_garden',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('m_id', models.AutoField(db_column='m_id', primary_key=True, serialize=False)),
                ('m_name', models.CharField(db_column='m_name', max_length=20)),
            ],
            options={
                'db_table': 'tb_main',
            },
        ),
        migrations.CreateModel(
            name='ModeratorDetails',
            fields=[
                ('mod_id', models.IntegerField(db_column='mod_id', primary_key=True, serialize=False)),
                ('mod_name', models.CharField(db_column='m_name', max_length=30)),
                ('mod_phno', models.CharField(db_column='m_phno', max_length=10)),
                ('mod_email', models.CharField(db_column='m_email', max_length=30)),
                ('mod_passwd', models.CharField(db_column='m_passwd', max_length=30)),
                ('mod_pic', models.ImageField(db_column='m_pic', upload_to='Moderator/')),
            ],
            options={
                'db_table': 'tb_moderator',
            },
        ),
        migrations.CreateModel(
            name='NurseryProduct',
            fields=[
                ('p_id', models.AutoField(db_column='p_id', primary_key=True, serialize=False)),
                ('prod_no', models.CharField(db_column='prod_no', max_length=20)),
                ('p_name', models.CharField(db_column='p_name', max_length=20)),
                ('p_desc', models.CharField(db_column='p_desc', max_length=200)),
                ('p_dimension', models.CharField(db_column='p_dimension', max_length=30)),
                ('p_location', models.CharField(db_column='p_location', max_length=20)),
                ('p_color', models.CharField(db_column='p_color', max_length=10)),
                ('p_sales_package', models.CharField(db_column='p_package', max_length=20)),
                ('p_material', models.CharField(db_column='p_material', default='', max_length=20)),
                ('p_shape', models.CharField(db_column='p_shape', default='', max_length=20)),
                ('p_qty', models.IntegerField(db_column='p_qty', null=True)),
                ('p_type', models.CharField(db_column='p_type', default='', max_length=20)),
                ('p_suitable_for', models.CharField(db_column='p_suitable', max_length=20)),
                ('p_seed', models.CharField(db_column='p_seed', max_length=20)),
                ('p_container', models.CharField(db_column='p_container', max_length=20, null=True)),
                ('p_caring_tips', models.CharField(db_column='p_tips', max_length=200, null=True)),
                ('p_features', models.CharField(db_column='p_features', max_length=100)),
                ('p_price', models.FloatField(db_column='p_price')),
                ('p_offer', models.FloatField(db_column='p_offer', default=0)),
                ('p_rating', models.FloatField(db_column='p_rating', default=0)),
                ('p_exp_days', models.IntegerField(db_column='p_expected_days')),
                ('p_img', models.ImageField(db_column='p_img', upload_to='Products/')),
                ('p_stock', models.IntegerField(db_column='p_stock', default=0)),
                ('p_status', models.CharField(default='available', max_length=20)),
                ('cat_id', models.ForeignKey(db_column='cat_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.categorydetails')),
                ('m_id', models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.maincategory')),
            ],
            options={
                'db_table': 'tb_nursery_product',
            },
        ),
        migrations.CreateModel(
            name='StandPotIdeas',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('posted_date', models.CharField(db_column='post_date', max_length=10)),
                ('item', models.CharField(db_column='item', max_length=10)),
                ('requirements', models.CharField(db_column='req', max_length=255)),
                ('design', models.ImageField(db_column='design', upload_to='Ideas/StandPot')),
                ('est_date', models.CharField(db_column='est_date', max_length=10)),
                ('budget', models.FloatField(db_column='budget', null=True)),
                ('reject_reason', models.CharField(db_column='r_reason', max_length=100)),
                ('completed_date', models.CharField(db_column='com_date', max_length=10)),
                ('delivered_date', models.CharField(db_column='del_date', max_length=10)),
                ('status', models.CharField(db_column='status', max_length=20)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.customerdetails')),
                ('mod_id', models.ForeignKey(db_column='mod_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nursery_app.moderatordetails')),
            ],
            options={
                'db_table': 'tb_standPot',
            },
        ),
        migrations.CreateModel(
            name='SellerReg',
            fields=[
                ('sell_id', models.AutoField(db_column='sel_id', primary_key=True, serialize=False)),
                ('sell_name', models.CharField(db_column='s_name', max_length=30)),
                ('sell_exp', models.IntegerField(db_column='s_exp')),
                ('doc_type', models.CharField(db_column='doc_type', max_length=20)),
                ('doc', models.FileField(db_column='seller_doc', upload_to='Seller/Documents')),
                ('about_me', models.CharField(db_column='abt_me', max_length=200)),
                ('status', models.CharField(db_column='status', max_length=10)),
                ('cust_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.customerdetails')),
            ],
            options={
                'db_table': 'tb_seller',
            },
        ),
        migrations.CreateModel(
            name='ReturnProducts',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('ord_date', models.CharField(db_column='ord_date', max_length=10)),
                ('del_date', models.CharField(db_column='del_date', max_length=10)),
                ('prod_img', models.ImageField(db_column='img', upload_to='return Product/')),
                ('status', models.CharField(db_column='status', max_length=20)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.customerdetails')),
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.nurseryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='RatingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_star', models.IntegerField(db_column='five_star')),
                ('four_star', models.IntegerField(db_column='four_star')),
                ('three_star', models.IntegerField(db_column='three_star')),
                ('two_star', models.IntegerField(db_column='two_star')),
                ('one_star', models.IntegerField(db_column='one_star')),
                ('craft_id', models.ForeignKey(db_column='c_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.craftdetails')),
                ('product_id', models.ForeignKey(db_column='p_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.nurseryproduct')),
            ],
            options={
                'db_table': 'tb_star',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_star', models.IntegerField(db_column='cust_star')),
                ('craft_id', models.ForeignKey(db_column='c_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.craftdetails')),
                ('customer', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.customerdetails')),
                ('product_id', models.ForeignKey(db_column='p_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.nurseryproduct')),
            ],
            options={
                'db_table': 'tb_rating',
            },
        ),
        migrations.CreateModel(
            name='ProductFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_date', models.CharField(db_column='f_date', max_length=20)),
                ('feedback', models.CharField(db_column='feed_back', max_length=100)),
                ('prod_img', models.ImageField(db_column='feed_img', upload_to='Feedback/')),
                ('craft_id', models.ForeignKey(db_column='cr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.craftdetails')),
                ('cust_id', models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.customerdetails')),
                ('nursey_id', models.ForeignKey(db_column='n_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.nurseryproduct')),
            ],
            options={
                'db_table': 'tb_feedback',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_no', models.CharField(db_column='ord_no', max_length=20, primary_key=True, serialize=False)),
                ('sell_type', models.CharField(db_column='s_type', max_length=10)),
                ('order_date', models.CharField(db_column='ord_date', max_length=10)),
                ('exp_delivery', models.CharField(db_column='exp_date', max_length=10)),
                ('shipping_address', models.CharField(db_column='shipping_address', max_length=200)),
                ('qty', models.IntegerField(db_column='qty')),
                ('total', models.FloatField(db_column='total')),
                ('order_status', models.CharField(db_column='ord_status', max_length=10)),
                ('craft_product', models.ForeignKey(blank=True, db_column='cr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.craftdetails')),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.customerdetails')),
                ('nursery_product', models.ForeignKey(blank=True, db_column='n_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.nurseryproduct')),
                ('seller_id', models.ForeignKey(db_column='seller_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.sellerreg')),
            ],
            options={
                'db_table': 'tb_order',
            },
        ),
        migrations.CreateModel(
            name='GardenProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amt', models.FloatField(db_column='total')),
                ('product_id', models.ForeignKey(db_column='p_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nursery_app.nurseryproduct')),
                ('req_id', models.ForeignKey(db_column='req_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.gardenideas')),
            ],
            options={
                'db_table': 'tb_gProducts',
            },
        ),
        migrations.AddField(
            model_name='gardenideas',
            name='mod_id',
            field=models.ForeignKey(db_column='mod_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nursery_app.moderatordetails'),
        ),
        migrations.AddField(
            model_name='craftdetails',
            name='seller_id',
            field=models.ForeignKey(db_column='sel_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.sellerreg'),
        ),
        migrations.AddField(
            model_name='categorydetails',
            name='m_id',
            field=models.ForeignKey(db_column='m_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.maincategory'),
        ),
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('cart_id', models.AutoField(db_column='c_id', primary_key=True, serialize=False)),
                ('sell_type', models.CharField(db_column='s_type', max_length=10)),
                ('qty', models.IntegerField(db_column='qty')),
                ('total', models.FloatField(db_column='total')),
                ('craft_product', models.ForeignKey(blank=True, db_column='cr_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.craftdetails')),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.customerdetails')),
                ('nursery_product', models.ForeignKey(blank=True, db_column='n_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.nurseryproduct')),
                ('seller_id', models.ForeignKey(db_column='seller_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.sellerreg')),
            ],
            options={
                'db_table': 'tb_cart',
            },
        ),
    ]
