# Generated by Django 3.2.5 on 2021-10-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnProducts',
        ),
    ]
