# Generated by Django 3.2.5 on 2021-10-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0002_delete_returnproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnProducts',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('ord_date', models.CharField(db_column='ord_date', max_length=10)),
                ('del_date', models.CharField(db_column='del_date', max_length=10)),
                ('prod_img', models.ImageField(db_column='img', upload_to='return Product/')),
                ('reason', models.CharField(db_column='return_reason', max_length=100)),
                ('status', models.CharField(db_column='status', max_length=20)),
                ('cust_id', models.ForeignKey(db_column='cust_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.customerdetails')),
                ('prod_id', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, to='nursery_app.nurseryproduct')),
            ],
            options={
                'db_table': 'tb_returnproduct',
            },
        ),
    ]
