# Generated by Django 3.2.5 on 2021-10-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0003_returnproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnproducts',
            name='cust_id',
        ),
        migrations.RemoveField(
            model_name='returnproducts',
            name='del_date',
        ),
        migrations.RemoveField(
            model_name='returnproducts',
            name='ord_date',
        ),
        migrations.RemoveField(
            model_name='returnproducts',
            name='prod_id',
        ),
    ]
