# Generated by Django 3.2.5 on 2021-10-09 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursery_app', '0005_returnproducts_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproducts',
            name='cust_id',
            field=models.ForeignKey(db_column='cust_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='nursery_app.customerdetails'),
            preserve_default=False,
        ),
    ]
